# Generated by Django 3.2.6 on 2021-08-31 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='weather',
            table='weather_db',
        ),
    ]
