# Generated by Django 3.2.6 on 2021-09-01 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather_page', '0002_alter_weather_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='name',
            new_name='city_name',
        ),
        migrations.AddField(
            model_name='weather',
            name='temp',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
